"""
project 2 euler problem



Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
 exceed four million, find the sum of the even-valued terms.

"""

term, a, b = 4000000, 0, 1

total = 0
for i in xrange(term):
    a, b = b, a+b

    # only concern with b values that are less 4,000,000
    if b < 4000000:
        if b % 2 == 0:
            total += b
    else:
        break



print(total)
